[package]
name = "path-tracer"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = {version ="0.29.2",features = ["glam-assert"]}
image = { version = "0.25.5", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.10.0"
tobj = "4.0.2"
